[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings for verification
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200

# Gas optimization settings - IMPORTANT for exact match
via_ir = false
force = false

# Verification settings - CRITICAL for exact match
bytecode_hash = "none"
cbor_metadata = false

# Additional settings for exact match
revert_strings = "default"
sparse_mode = false

# Remappings for clean imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Network configurations
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "base-sepolia" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
